name: Security Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  security:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: j7an/shared-workflows/.github/workflows/security-scan.yml@d76ca3a6d121dabbab2d7a64118968edc1f14da2 # v4.5.1
    with:
      support_merge_group: true
      codeql_queries: +security-and-quality
